// GENERATED CODE - DO NOT MODIFY BY HAND
// (Generated by 'scripts/generate-inputs.ts')
import * as core from '@actions/core';

const keys: [key: string, required: boolean][] = [
  ['command', true],
  ['allowed_contexts', true],
];

export type Inputs = {
  command: string;
  allowed_contexts: string;
};

export const getInputs = (): Inputs => {
  const inputs = Object.create(null);
  for (const [key, required] of keys) {
    const v = core.getInput(key, { required });
    inputs[key] = !required && v === '' ? null : v;
  }
  return inputs as Inputs;
};
