name: Audit GitHub Actions

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - '.github/**'
      - 'action.yaml'
  push:
    branches:
      - main
      - 'releases/*'
    paths:
      - '.github/**'
      - 'action.yaml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup
        with:
          install: 'false'

      - name: Run actionlint
        run: actionlint -color

  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup
        with:
          install: 'false'

      - name: Run zizmor
        run: zizmor .
