name: 'Continuous Integration'

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Commitlint
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: pnpm exec commitlint --from="$BASE_SHA" --to="$HEAD_SHA" --verbose

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup

      - run: pnpm build

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format:check

      - name: Generate
        run: |
          pnpm generate
          git diff --exit-code || exit 1

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    needs: build_and_test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release
