name: 'Continuous Integration'

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ./.github/actions/setup-node

      - run: pnpm build

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: Generate
        run: |
          pnpm generate
          git diff --exit-code || exit 1

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    needs: build_and_test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup-node

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release
